### ISSUE TITLE
Documentation about installation requirements/steps.

### ISSUE THREAD

**Issue by billhathaway** [MCLD/greatreadingadventure#1]
The website looks great, but there is no documentation I could find about what is needed to install this.

**Comment by MCLD** [comment]
Hey!

Check out our SourceForge page for download of the packaged app and instructions. The wiki has a bunch of stuff.

https://sourceforge.net/p/thegreatreadingadventure/

**Comment by lscritch** [comment]
Might want to include a template for a privacy policy, re the Children's Online Privacy Protection Act of 1998, (15 U.S.C. 6501, et seq.,) or COPPA.

**Comment by MCLD** [comment]
Not a bad idea. If someone drafts one, we can put it into the installation.
