### ISSUE TITLE
Error when trying to edit Tenant admin user.

### ISSUE THREAD

**Issue by justinmeiners** [MCLD/greatreadingadventure#112]
Steps:
1. Create a new Organization
2. Select "Users" under Organization in control.
3. Attempt to edit user for new organization.

![tenant_user](https://cloud.githubusercontent.com/assets/3220045/14002737/6abb23ac-f113-11e5-97da-c3aeacddc1ed.png)

**Comment by haraldnagel** [comment]
You can actually just try to edit the users in the master tenant and hit this - I missed this in my Great Password Code Change earlier this year. I'll fix it.
