### ISSUE TITLE
Exception when trying to create a program.

### ISSUE THREAD

**Issue by justinmeiners** [MCLD/greatreadingadventure#138]
In the control room, attempting to create a new program with the "+" or "Add New Program" buttons throws the following exception.
![exception](https://cloud.githubusercontent.com/assets/3220045/14801621/f77ca4ce-0b07-11e6-82e4-7ed8456e4776.png)

**Comment by haraldnagel** [comment]
I've reproduced this. Will work on a fix.

**Comment by justinmeiners** [comment]
I see the issue. The tab container with id `"tc1"` is in the `editItemTemplate`, but not the `insertItemTempate`

That causes this line:
`var codePanel = dv.FindControl("tc1").FindControl("tp6") as AjaxControlToolkit.TabPanel;
`
to call `.FindControl("tp6"`) on null

**Comment by haraldnagel** [comment]
Exactly right. I'm about to check in a fix. :smile:
