### ISSUE TITLE
Exception when trying to download excel sheet for Program Reward Codes

### ISSUE THREAD

**Issue by justinmeiners** [MCLD/greatreadingadventure#142]
1. Edit a program in the control room.
2. Go to "Program Reward Codes" tab
3. Generate codes
4. Download excel file

![exception](https://cloud.githubusercontent.com/assets/3220045/14869938/f1561b1a-0c93-11e6-89e9-694cea46bb24.png)

**Comment by haraldnagel** [comment]
Hmm. This is concerning. It's working here on both my workstation as well as the servers where we have the software deployed. NuGet in Visual Studio is showing `DocumentFormat.OpenXml` installed in the `SRPUtilities` project. Do you have the `DocumentFormat.OpenXml.dll` file in your bin folder where the software is deployed?

**Comment by justinmeiners** [comment]
The DLL is not in the bin folder. 

In visual studio I see warning symbols next to that project in the references section. I am not familiar enough with visual studio to know what that means.

![warning](https://cloud.githubusercontent.com/assets/3220045/14871072/36010d1c-0c9c-11e6-8a25-d2d64b29d227.png)

**Comment by haraldnagel** [comment]
If you run `get-packages` in the NuGet console does it show the `DocumentFormat.OpenXml` package is installed?

**Comment by justinmeiners** [comment]
I tried both `Get-Packages` and reinstalled with `Update-Package –reinstall DocumentFormat.OpenXml`.


It is still shown as missing in the SRP, but not SRPUtilities project.

**Comment by haraldnagel** [comment]
Hmm. I thought I had removed references to it from the SRP project at some point. Are you operating off the latest code? If you right-click that yellow-warning reference and remove it does it work?

**Comment by justinmeiners** [comment]
Today I did a fresh pull. Republished and it is now working. It also fixed #143

**Comment by haraldnagel** [comment]
Weird. I wonder what was wrong. If you see this again, please open another issue or contact me! :rage1:
