### ISSUE TITLE
Import/Export Events "Download Excel file" does nothing

### ISSUE THREAD

**Issue by justinmeiners** [MCLD/greatreadingadventure#143]
1. Go to "Import/Export Events" in control room
2. Press "Download Excel File"

**Result:**
 Nothing happens

**Expected:**

Perhaps this is a misunderstanding on my part about this feature. I assume that "download excel file" would download an excel file of the events currently stored in the system.

**Comment by haraldnagel** [comment]
Your expectation is correct. Is it possible that your pop-up blocker wouldn't allow the window to open?

**Comment by justinmeiners** [comment]
I am pretty certain this is not the case. It seems more likely it is related to the other excel sheet problem.

**Comment by haraldnagel** [comment]
Hmm. I'm not sure - I used a totally different approach for this export, though I could be wrong.
