### ISSUE TITLE
Survey URLs do not work without forward slash.

### ISSUE THREAD

**Issue by justinmeiners** [MCLD/greatreadingadventure#150]
In the Control Room I attempt to generate a URL to a survey using the URL wizard.

The result is something like this:

```
<iframe allowtransparency="true" frameborder="0" id="srvy" style="border:0px;padding-bottom:4px;" 
    src="FramedSurvey.aspx?SID=1&SSrc=4&SSrcID=1" 
    height="700" width="800">
    </iframe>

```

However this link fails to work anywhere unless a forward slash is included before the URL.

```
        ....
    src="/FramedSurvey.aspx?SID=1&SSrc=4&SSrcID=1" 
```

Should the forward slash be included? Perhaps this is an issue with my server configuration and not with the program.

**Comment by haraldnagel** [comment]
I'm not sure that I've ever used the FramedSurvey capability - we've only used the survey/test capability by manually adding the questions into the GRA.

**Comment by justinmeiners** [comment]
What do you mean by adding them manually? Creating a custom HTML form that posts to the survey?

**Comment by haraldnagel** [comment]
When we do the literacy test we use the Test/Survey functionality in the `Management` tab and put in each question using the "question list" button at the bottom.
