### ISSUE TITLE
URLs generated from Handlers are not absolute paths.

### ISSUE THREAD

**Issue by justinmeiners** [MCLD/greatreadingadventure#164]
**Reproduction**
1. Create a badge with an image in the control room.
2. Login to the dashboard.
3. The small image URL is correct but the large URL in the Badge info popup is relative and not expanded.

Screenshot:

![badge_url](https://cloud.githubusercontent.com/assets/3220045/15131024/de18b0ec-1609-11e6-9930-07a1b81cbe02.png)

**Discussion**
This only occurs on my live server and not my local machine. Perhaps this is an issue with my server configuration?

**Comment by haraldnagel** [comment]
This might be a duplicate, I think I fixed this in d4d63a0, specifically [here](https://github.com/MCLD/greatreadingadventure/commit/d4d63a0adb90449ca433c91eb6c93355d84cd883#diff-bf6fc77d7a4bd2133c3299ccc27f3e46R64). Let me know if that doesn't fix the issue.

**Comment by justinmeiners** [comment]
You are probably correct I have pulled, but not deployed your latest changes. Thank you!
