### ISSUE TITLE
Event excel sheet import fails if branch cell is left empty.

### ISSUE THREAD

**Issue by justinmeiners** [MCLD/greatreadingadventure#167]
**Reproduction**
1. Download excel sheet of events.
2. Modify sheet to represent new event.
3. Leave "Branch" empty indicating the event has no branch selected.
4. Upload and import

**Expected**
Events should be able to imported with no branch assigned, in the same way that they can be created without a branch.

**Actual**
Import fails without branch matching one in program.

**Discussion**
I have a fix for this.

**Comment by haraldnagel** [comment]
:thumbsup: go ahead and submit the fix!
