### ISSUE TITLE
Event excel sheet export ignores time component of DateTime

### ISSUE THREAD

**Issue by justinmeiners** [MCLD/greatreadingadventure#168]
**Reproduction**
1. Download excel sheet of events when there are events in the system with a date and time.

**Expected**
Exported excel sheet should have "time" as well as date to allow spreadsheet to easily configure time.

**Actual**
The excel sheet exports a simplified date format that truncates time information.

**Discussion**
I have a fix for this.

**Comment by haraldnagel** [comment]
I'm interested to see your fix in this but I'm concerned - the sheets as they exist can be exported and imported back into the system. I think I worked around this by changing the cell format once I'd exported it to a format that had date and time in it. If you submit this do it as a separate PR so we can look at it and ensure the exports will be able to be imported.

**Comment by justinmeiners** [comment]
When you say that the sheets can be exported and imported, do you mean that a direct export and import with no modifications should have no impact on the event list?

**Comment by haraldnagel** [comment]
I'm sorry, I was really unclear there! Yes, doing the import will cause duplicates. :cry: 

What I just meant is that the export file and the import file should be exactly the same format so that you can use an export file as a sample for formatting in order to do an import.

**Comment by justinmeiners** [comment]
Ok, that makes sense and is how I assumed it would work. I will ensure this works properly before submitting it.

**Comment by haraldnagel** [comment]
Thanks! I just did an export on our data and in addition to giving an error (probably due to events with long-ish HTML descriptions) it also exports dates with no time information? I had thought it was exporting time information but it was just in a weird format and the cell formatting had to be adjusted. This is definitely a bug that should be addressed.
