### ISSUE TITLE
Badge names are truncating at 50 characters

### ISSUE THREAD

**Issue by haraldnagel** [MCLD/greatreadingadventure#169]
**Problem:**
Entering a badge name longer than 50 characters causes it to truncate at 50 characters.

**Reproduction:**
Happens every time.
1. Add a badge with a name longer than 50 characters.
2. Note that the name truncated at 50 characters.

**Expected behavior:**
Badge names shouldn't truncate up to 255 characters.

**Comment by justinmeiners** [comment]
This is a helpful fix for me as well.

**Comment by haraldnagel** [comment]
@justinmeiners This one requires a database table change so you'll probably want to use Schema Compare to migrate
