### ISSUE TITLE
Parental consent does not hide/show as it is programmed.

### ISSUE THREAD

**Issue by justinmeiners** [MCLD/greatreadingadventure#186]
**Description**
See code for context: https://github.com/MCLD/greatreadingadventure/blob/deeedfcd97c760ce09a45d1ffdb4bdb73dc10fd3/SRP/Controls/PatronRegistration.ascx#L889

The parental consent section has several snippets like the following
`visible = '<%# int.Parse(RegistrationAge.Text.Length==0 ? "0" : RegistrationAge.Text) < 18 %>'`

Part of that code is checking to see whether the registration age is greater than 18, however, the template is evaluated when the page loads, not when this section of the registration appear. This check always fails because RegistrationAge never has any text in it when the page loads.

This results in the parental consent field being shown regardless of whether the applicant is an adult. Several of these checks also appear redundant given that the parent element is hidden by the same logic.

**Discussion**

I think this unintended functionality of showing the consent form for adults is desirable. It would be helpful to write out program rules in the parental consent description and for both adults and children's parents to accept. If this current state is the desired functionality the 18 check code should be removed and perhaps the wording should be changed slightly (Maybe label Parent/Guardian). The checkbox should also not be marked by default to require an active commitment.

In its current form it just doesn't appear to be doing what it is programmed to do.

**Comment by justinmeiners** [comment]
@haraldnagel Does my diagnoses here sound correct?

**Comment by haraldnagel** [comment]
I'm so sorry that I haven't looked into this. Things have been crazy as you'd expect.

Without diving in it seems to me that perhaps that line you pasted is being re-evaluated as the page posts back so if `RegistrationAge.Text` is being set on an earlier step in the registration process it might actually be recomputing when it gets to this step. If it's not happening in that order then you are correct in that logic is probably not valid.

We were told by legal that we did not need to ask for parental consent so I will confess to not having tested a lot with that field enabled in registration.

I can try to look at this code a little closer (maybe later today) and give a better assessment.

**Comment by justinmeiners** [comment]
No rush. Whenever it is convenient for you.

**Comment by haraldnagel** [comment]
I tried to reproduce this and couldn't get the parental consent thing to come up at all. There's definitely something wrong but I'm just not going to have time to track it down.

If you have a proposed solution to this I'd say go with it as long as it's going to allow us to toggle off the consent checkbox since we definitely don't want to have it enabled here.

Sorry about the delay in getting back to you on this issue.
