### ISSUE TITLE
Branch/Library label is visible in Badge Gallery when dropdown is hidden.

### ISSUE THREAD

**Issue by justinmeiners** [MCLD/greatreadingadventure#190]
In the "Badge Gallery" dropdown lists are programmed to hide when they have 1 or fewer items. (See Badges/Default.aspx.cs").

When the Branch/Library dropdown is hidden, its label is not. This leaves an empty label on the badge gallery.

**Comment by haraldnagel** [comment]
Are you taking this or should I fix?

**Comment by justinmeiners** [comment]
I can get this. Ill send you an email this week about some things.
