### ISSUE TITLE
Email regular expression problems

### ISSUE THREAD

**Issue by haraldnagel** [MCLD/greatreadingadventure#192]
**Problem:**
Email address regular expression does not accept email addresses with an initial capital letter.

**Reproduction:**
Happens every time.
1. Modify a patron in the control room
2. Change their email address to one with a capital letter as the first letter
3. Note the validator won't accept it

**Expected behavior:**
Accept valid email addresses as per [RFC 5321](https://tools.ietf.org/html/rfc5321#section-2.3.11).

**Discussion:**
Not only is the regular expression invalid, there are different regular expressions used throughout the application for email address verification. Validating email addresses with regex is probably not the best long-term idea but for now using the expression on <http://emailregex.com/> seems to make the most sense.

**Comment by justinmeiners** [comment]
I have run into this issue in the past. I think certain regex implementations are better than others. I know the agreed upon Stackoverflow wisdom is that regex can't validate all possible emails in the standard, but I really question how many real life email addresses fall into those extreme edge cases.

**Comment by haraldnagel** [comment]
I was thinking that maybe the regex should show a message that says something like "your email address does not appear to be correct, please verify it" or something similar so that we're doing some checking but not restricting sign-up in case the regex is wrong.

That being said, it seems like this particular regex would work in nearly every case, maybe we just leave it as-is until we get reports that someone's having a problem.

**Comment by justinmeiners** [comment]
Either of those sound like a good solution to me. (and obviously it is up to you, I was just tossing in my comment.)

I imagine someone with a tricky email has more sign up problems than the GRA.

**Comment by haraldnagel** [comment]
Well I appreciate your feedback on anything in the project, it's good to have two brains working on this stuff rather than one!
