### ISSUE TITLE
Program DALassigns values to empty object

### ISSUE THREAD

**Issue by justinmeiners** [MCLD/greatreadingadventure#195]
See this section: https://github.com/MCLD/greatreadingadventure/blob/master/SRP_DAL/Programs.cs#L586

This is a similar issue to #188. For some reason all of these DAL sections contain an empty "result" object which is easy to mistakenly use when copy/pasting.

**Comment by haraldnagel** [comment]
There must have been something in the code that generated this DAL code which, in addition to making typical CRUD methods also made static ones. I'm not sure why except for developer convenience. There are all kinds of opinions all over the Web as to why you might make your classes static versus instance but I'm at a loss as to why you'd put both in the same class.

In at least one place I removed the static approach at the start of working on the project but I just didn't for any additional situations.

My thoughts are to address the bugs where we find them with this (fix the copy/paste issues) and have the overall plan to be migrate to a real ORM for the next major release.
