### ISSUE TITLE
Goal recalculation does not always happen.

### ISSUE THREAD

**Issue by justinmeiners** [MCLD/greatreadingadventure#199]
The Goal Calculation needs to take place before any points or codes are entered, the current chosen location is the login and registratino. However, it's possible to login through the family list or through other means. Perhaps a better event should be used.

**Comment by haraldnagel** [comment]
Hmm the only other way to log in is through the family list I think. If you hooked that as well I think you'd be catching everything.

**Comment by justinmeiners** [comment]
I logged this bug as a reminder, I now have a fix in mind. Today we had some big problems with the goal, and I tracked it to the "Add Family Member" section. It has separate fields than the normal registration so it was possible to register with a goal of zero, and award yourself all the badges in the first entry.

**Comment by justinmeiners** [comment]
Here is another location where badges are awarded before the goal is ready: https://github.com/MCLD/greatreadingadventure/blob/master/SRP/Controls/AddFamilyMemberControl.ascx.cs#L253
