### ISSUE TITLE
Center points column in PatronPoints ControlRoom view.

### ISSUE THREAD

**Issue by justinmeiners** [MCLD/greatreadingadventure#206]
A librarian had some confusion about what the "PatronPoints" view in the ControlRoom was displaying. It would be helpful if the "Points Earned" column was centered to separate it from the "Reason Points were awarded".

You can add this to my list.

![challenge screenshot](https://cloud.githubusercontent.com/assets/3220045/15986267/d14ecdda-2fc0-11e6-8e6c-90403b8c4b42.png)

**Comment by haraldnagel** [comment]
Even left-aligned would look better. Either works!
