### ISSUE TITLE
Fails to configure running locally in Visual Studio

### ISSUE THREAD

**Issue by justinmeiners** [MCLD/greatreadingadventure#36]
***Note:*** This bug is related to Harald's Branch

- Perform a fresh checkout and run GRA in Visual Studio and navigate to /ControlRoom/Configure.aspx

- After successfully filling out the configuration process I receive a database error (See Screenshots).

![config1](https://cloud.githubusercontent.com/assets/3220045/12184444/7eeb5704-b552-11e5-92a4-42d964d2a171.png)

![config2](https://cloud.githubusercontent.com/assets/3220045/12184521/ee482aaa-b552-11e5-8c50-32da97103fe4.png)

![config3](https://cloud.githubusercontent.com/assets/3220045/12184447/82ed050a-b552-11e5-953a-d32db6a4c727.png)

**Comment by haraldnagel** [comment]
I believe this is happening because there are already artifacts in the database that it is trying to create via script. It probably makes sense for us to check for the existence of those items before we try to create them.

**Comment by justinmeiners** [comment]
You are right, I actually just found out it was colliding with content from an old version. I assumed separate projects would not use the same database. Thanks!

**Comment by justinmeiners** [comment]
This issue can be closed.

**Comment by haraldnagel** [comment]
I'm going to close this but in the long term I'd like to find a solution to better handle the initial database creation if the script blew up halfway through.
