### ISSUE TITLE
Badge/Award Indicator animation 

### ISSUE THREAD

**Issue by justinmeiners** [MCLD/greatreadingadventure#37]
***Note:*** This bug is related to Harald's Branch

When clicking the buttons to change from "Points Earned to "Challenges Completed" or"Badges Completed" and the number animates ticking down until reaching the value. (I assume this animation or at least the triple digit part should only be for "Points Earned")

![error](https://cloud.githubusercontent.com/assets/3220045/12184613/82f1b266-b553-11e5-8afe-629d1f795e97.png)

**Comment by haraldnagel** [comment]
When I added the odometer animation I wasn't really concerned about it rolling back the number as the user selects another display option. I've briefly looked into trying to remove the odometer animation once the page has loaded (by binding to the [`odometerdone` event](https://github.com/HubSpot/odometer/issues/31) and using it to remove the `odometer` CSS class). Unfortunately, the ability to remove the `odometer` CSS class seems to not be a feature of that particular JavaScript project - it causes the numeric display to malfunction (it adds 8's between each digit?).

For now I don't see any problems with the current behavior. It's possible to use the other odometer animation method ([count](http://github.hubspot.com/odometer/#advanced)) to minimize the animation or remove `odometer.js` entirely if the animation is too distracting. Is this a critical issue? Would one of these workarounds work for now?

We could also file an issue with [the `odometer` project](https://github.com/HubSpot/odometer) to ask if there's a way to disable the animation once it's fully loaded.

**Comment by justinmeiners** [comment]
Ok no worries. It doesn't seem broken or anything, I just thought it was a little odd. Could maybe the other numbers be changed to be 3 digits like the point spinner? I think the biggest issue is the abrupt change from "XXX" to "000" to suddenly "0".

**Comment by haraldnagel** [comment]
I agree that it's a little weird. In our currently-running winter program we have about 2,000 points earned, around 3,000 badges awarded, and 500 challenges completed so it looks a littel bit less awkward. I'll continue thinking about this and looking into options. Let me know if you have any other ideas or find any options!

**Comment by haraldnagel** [comment]
I'm going to close this for now.
