### ISSUE TITLE
Enter book details panel does not respond to "Enter"

### ISSUE THREAD

**Issue by justinmeiners** [MCLD/greatreadingadventure#38]
(Harald's Branch)

The enter book details panel does not seem to interpret "enter" unless you are editing a field. If "enter" is pressed while editing a field the panel flashes away and then reappears.

![enter_bug](https://cloud.githubusercontent.com/assets/3220045/12187602/7e2d76d6-b56a-11e5-9b72-37e29a5505ba.png)

**Comment by haraldnagel** [comment]
Probably similar to the problem in #23 - enter on these modal pop-ups doesn't seem to trigger the submit button.

**Comment by haraldnagel** [comment]
Or maybe not since that issue was with JavaScript off.
