### ISSUE TITLE
Ability to link to participant's library in the footer

### ISSUE THREAD

**Issue by k7hpn** [MCLD/greatreadingadventure#460]
We don't currently have a facility to link participants back to their library despite the fact that we have URLs stored for each library. Perhaps a flag somewhere that when toggled on puts a link in the footer (or elsewhere) linking to the participant's library.

(Suggested by Lindsey)

**Comment by madison-boman** [comment]
Directions from @k7hpn 
1) Add a system setting under "users" for "show link to participant's library in the footer"
2) Modify GRA.Controllers.Filter.UserFilter to check if that setting is set to true and if so put the user's library name and URL into a httpContext.Item
3) Modify SiteTagHelper (which outputs the footer) to also output in a line under the current footer something like "Visit <libraryname>" which links to the library's Web site - this will have to be localized as well
