### ISSUE TITLE
List of participating libraries

### ISSUE THREAD

**Issue by k7hpn** [MCLD/greatreadingadventure#461]
We have a list of all library locations by system, it would be nice to have a feature switch to toggle on a page to show that list to participants, possibly via a link in the footer.

(Suggested by Lindsey)

**Comment by madison-boman** [comment]
1) Have a page to display all participating libraries

- For systems with multiple branches, put the system name, then an unordered list of branches, that are linked under it
- For single libraries, just provide a link to it
- Follow accessibility syntax for links

2) Make link User site setting that can be toggled.
3) Provide a link below the InfoLinks in the footer, labeled "Participating Libraries"
