### ISSUE TITLE
User Can Enter Review: doesn't seem to persist or store state.

### ISSUE THREAD

**Issue by justinmeiners** [MCLD/greatreadingadventure#47]
(Harald's Branch)
In Control Room -> Programs -> Program List -> Edit Program

Try modifying the value of "User can enter review" and saving it. It doesn't seem to be keeping it's state.

**Comment by haraldnagel** [comment]
When I check the `User Can Enter Review` checkbox on the Program Add/Edit screen and hit save I'm seeing the `PatronReviewFlag` value in the `Programs` table being changed. Are you not seeing this behavior?

**Comment by justinmeiners** [comment]
This can be closed. Perhaps I got mine in a bad state. After checking out a fresh copy it seems to work.

**Comment by haraldnagel** [comment]
Ok. Feel free to re-open if you see this again.
