### ISSUE TITLE
Resolve issue with deprecated AddAutoMapper call

### ISSUE THREAD

**Issue by haraldnagel** [MCLD/greatreadingadventure#489]
It appears that [`services.AddAutoMapper()`](https://github.com/MCLD/greatreadingadventure/blob/d01270ec7370bfc34d9fa8f1482db094e694779f/src/GRA.Web/Startup.cs#L444) is deprecated and [now needs types or assemblies passed in to it](https://github.com/AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection).

**Comment by Vanderlan** [comment]
+1

**Comment by haraldnagel** [comment]
This was partially addressed in commit 18ac31f6 and PR #504 Add assemblies to AutoMapper service injection
