### ISSUE TITLE
User registration - cannot press previous with required fields.

### ISSUE THREAD

**Issue by justinmeiners** [MCLD/greatreadingadventure#50]
During user registration, if there is a required field that has a validation requirement not met, the user cannot press previous.

**Comment by haraldnagel** [comment]
This might be as easy as adding `CausesValidation="False"` in the `<asp:Button>` controls.

**Comment by justinmeiners** [comment]
Would you like me to test it and make this change?

**Comment by haraldnagel** [comment]
Go for it!
