### ISSUE TITLE
Mismatched Jquery version referenced in code compared to in Scripts folder.

### ISSUE THREAD

**Issue by justinmeiners** [MCLD/greatreadingadventure#51]
Latest version of GRA showed a lot of javascript errors. Looking at the page source, jQuery is referenced as  `<script src="/Scripts/jquery-2.1.4.min.js"></script>`

That link does not exist because jQuery version 2.0.0 appears to be the version included in the SRP/Scripts folder.

**Comment by haraldnagel** [comment]
This was an error on my part. The latest code and 3.0.1 revision should fix it. Sorry about that!

**Comment by haraldnagel** [comment]
I'm going to close this, if it's still an issue please let me know.
