### ISSUE TITLE
Program flag "PatronReviewFlag" doesn't seem to do anything.

### ISSUE THREAD

**Issue by justinmeiners** [MCLD/greatreadingadventure#52]
I was unsure what the "PatrongReviewFlag" did. After a search it doesn't appear to affect the program at all. Am I missing something?

Here is a list of usages:

> Find all "PatronReviewFlag", Find Results 1, Entire Solution, ""
  C:\cygwin64\home\justinm\develop\gra\SRP\ControlRoom\Modules\Install\CreateSchema.sql(10366):	@PatronReviewFlag BIT,
  C:\cygwin64\home\justinm\develop\gra\SRP\ControlRoom\Modules\Install\CreateSchema.sql(10417):		PatronReviewFlag,
  C:\cygwin64\home\justinm\develop\gra\SRP\ControlRoom\Modules\Install\CreateSchema.sql(10468):		@PatronReviewFlag,
  C:\cygwin64\home\justinm\develop\gra\SRP\ControlRoom\Modules\Install\CreateSchema.sql(10631):	@PatronReviewFlag BIT,
  C:\cygwin64\home\justinm\develop\gra\SRP\ControlRoom\Modules\Install\CreateSchema.sql(10680):	PatronReviewFlag = @PatronReviewFlag,
  C:\cygwin64\home\justinm\develop\gra\SRP\ControlRoom\Modules\Install\CreateSchema.sql(21720):	[PatronReviewFlag] [bit] NULL,
  C:\cygwin64\home\justinm\develop\gra\SRP\ControlRoom\Modules\Install\InsertInitialData-MultiplePrograms.sql(1685):	[PatronReviewFlag],
  C:\cygwin64\home\justinm\develop\gra\SRP\ControlRoom\Modules\Install\InsertInitialData-MultiplePrograms.sql(1785):	[PatronReviewFlag],
  C:\cygwin64\home\justinm\develop\gra\SRP\ControlRoom\Modules\Install\InsertInitialData-MultiplePrograms.sql(1885):	[PatronReviewFlag],
  C:\cygwin64\home\justinm\develop\gra\SRP\ControlRoom\Modules\Install\InsertInitialData-MultiplePrograms.sql(1985):	[PatronReviewFlag],
  C:\cygwin64\home\justinm\develop\gra\SRP\ControlRoom\Modules\Install\InsertInitialData.sql(1685):	[PatronReviewFlag],
  C:\cygwin64\home\justinm\develop\gra\SRP\ControlRoom\Modules\Programs\ProgramsAddEdit.aspx(409):                                            <asp:CheckBox ID="PatronReviewFlag" runat="server" Checked='<%# (bool)Eval("PatronReviewFlag") %>' ReadOnly="False"></asp:CheckBox>
  C:\cygwin64\home\justinm\develop\gra\SRP\ControlRoom\Modules\Programs\ProgramsAddEdit.aspx.cs(124):                    //obj.PatronReviewFlag = ((CheckBox)((DetailsView)sender).FindControl("PatronReviewFlag")).Checked;
  C:\cygwin64\home\justinm\develop\gra\SRP\ControlRoom\Modules\Programs\ProgramsAddEdit.aspx.cs(216):                    obj.PatronReviewFlag = ((CheckBox)((DetailsView)sender).FindControl("tc1").FindControl("tp1").FindControl("PatronReviewFlag")).Checked;
  C:\cygwin64\home\justinm\develop\gra\SRP_DAL\Programs.cs(44):        private bool myPatronReviewFlag;
  C:\cygwin64\home\justinm\develop\gra\SRP_DAL\Programs.cs(159):        public bool PatronReviewFlag
  C:\cygwin64\home\justinm\develop\gra\SRP_DAL\Programs.cs(161):            get { return myPatronReviewFlag; }
  C:\cygwin64\home\justinm\develop\gra\SRP_DAL\Programs.cs(162):            set { myPatronReviewFlag = value; }
  C:\cygwin64\home\justinm\develop\gra\SRP_DAL\Programs.cs(493):                result.PatronReviewFlag = bool.Parse(dr["PatronReviewFlag"].ToString());
  C:\cygwin64\home\justinm\develop\gra\SRP_DAL\Programs.cs(584):                this.PatronReviewFlag = bool.Parse(dr["PatronReviewFlag"].ToString());
  C:\cygwin64\home\justinm\develop\gra\SRP_DAL\Programs.cs(706):            arrParams[14] = new SqlParameter("@PatronReviewFlag", GRA.SRP.Core.Utilities.GlobalUtilities.DBSafeValue(o.PatronReviewFlag, o.PatronReviewFlag.GetTypeCode()));
  C:\cygwin64\home\justinm\develop\gra\SRP_DAL\Programs.cs(782):            arrParams[15] = new SqlParameter("@PatronReviewFlag", GRA.SRP.Core.Utilities.GlobalUtilities.DBSafeValue(o.PatronReviewFlag, o.PatronReviewFlag.GetTypeCode()));
  C:\cygwin64\home\justinm\develop\gra\GRA.Database\dbo\Stored Procedures\app_Programs_Insert.sql(17):	@PatronReviewFlag BIT,
  C:\cygwin64\home\justinm\develop\gra\GRA.Database\dbo\Stored Procedures\app_Programs_Insert.sql(68):		PatronReviewFlag,
  C:\cygwin64\home\justinm\develop\gra\GRA.Database\dbo\Stored Procedures\app_Programs_Insert.sql(119):		@PatronReviewFlag,
  C:\cygwin64\home\justinm\develop\gra\GRA.Database\dbo\Stored Procedures\app_Programs_Update.sql(18):	@PatronReviewFlag BIT,
  C:\cygwin64\home\justinm\develop\gra\GRA.Database\dbo\Stored Procedures\app_Programs_Update.sql(67):	PatronReviewFlag = @PatronReviewFlag,
  C:\cygwin64\home\justinm\develop\gra\GRA.Database\dbo\Tables\Programs.sql(17):    [PatronReviewFlag]    BIT           NULL,
  Matching lines: 28    Matching files: 9    Total files searched: 1591

**Comment by haraldnagel** [comment]
It looks like perhaps this flag was an inadvertent victim of me clobbering the old logging control and making my own from scratch (oops! :fearful:). I see in the v2.2.1 codebase that it's referenced in the old [SimpleLoggingControl.ascx.cs](https://github.com/MCLD/greatreadingadventure/blob/v2.2.1/SRP/Controls/SimpleLoggingControl.ascx.cs#L28).

We talked a lot about reviews here and decided against collecting them as we didn't really have any ideas as to what to do with them at the end of the program. We also didn't want one user to see another user's reviews due to CIPA concerns. As long as this toggle is enforced I don't see anything wrong with adding this functionality back in.
