### ISSUE TITLE
Change drawings to not use client-side evaluations

### ISSUE THREAD

**Issue by iafb** [MCLD/greatreadingadventure#553]
Union in drawing queries is causing a client-side evaluation to be performed.

**Comment by haraldnagel** [comment]
Relates to #218 Meta issue: disable client-side evaluation on EF calls

**Comment by k7hpn** [comment]
@iafb can you take a look at this since I'm not sure client-side even works anymore.

**Comment by iafb** [comment]
Will take a look and ensure it all still works.

**Comment by iafb** [comment]
@k7hpn Support for Union operations was added in [EF Core 3.0](https://devblogs.microsoft.com/dotnet/announcing-entity-framework-core-3-0-preview-7-and-entity-framework-6-3-preview-7/). Upgrading the GRA from Core 2.2 to .NET 5 added in those changes and testing confirms that the issue was resolved.
