### ISSUE TITLE
TranslationEarningsAsync uses client side evaluation for Sum()

### ISSUE THREAD

**Issue by k7hpn** [MCLD/greatreadingadventure#592]
[`TranslationEarningsAsync()`](https://github.com/MCLD/greatreadingadventure/blob/develop/src/GRA.Data/Repository/UserLogRepository.cs#L327-L366) uses client side evaluation (#218) for Sum(). I believe this has something to do with the `GroupJoin()`.

**Comment by k7hpn** [comment]
@iafb Dan, can you see if this is still an issue or if it's resolved with our EF upgrade?

**Comment by iafb** [comment]
@k7hpn It looks like the change away from using `GroupJoin()` for `TranslationEarningsAsync()` was included as part of the compatibility changes in the .NET 5 upgrade (#685). I just tested to confirm everything's working without using client side evaluation and I think this issue can be closed.

**Comment by k7hpn** [comment]
Closing this out, yay! 🥳
