### ISSUE TITLE
Installation/Upgrade instructions for version 4.2.1

### ISSUE THREAD

**Issue by Jason-42** [MCLD/greatreadingadventure#859]
Are the installation/upgrading instructions for the latest version 4.2.1?  I am on 4.2.0 and looking to install the update before we start our next reading program.  The link gives an error when you click on it to view the instructions.

http://manual.greatreadingadventure.com/en/v4.2/installation

Thank you

**Comment by k7hpn** [comment]
I'm sorry about that 404. I found the broken link in the release notes and fixed it, the correct link is this one: [Upgrading](http://manual.greatreadingadventure.com/en/v4.2.0/installation/upgrading/). Thanks for reporting this!

Going from 4.2.0 to 4.2.1 should be pretty seamless. Let us know how it goes and if you run in to any issues!

**Comment by Jason-42** [comment]
Thank you very much for that.  Have a great day.

Best Regards,

Jason Gesullo | Director of Technical Operations
C: 801.664.5034<tel:801-664-5034>
O: 801.253.4541<tel:801.253.4541>
***@***.******@***.***>
1314 W 11400 S
South Jordan, UT 84095
www.executech.com<http://www.executech.com/>

[signature_1679611770]<http://bit.ly/executech>
This e-mail may contain information that is confidential, proprietary, or “non-public personal information”.  The Confidential Information is disclosed conditioned upon your agreement that you will treat it confidentially and in accordance with applicable law, ensure that such data isn’t used or disclosed except for the limited purpose for which it’s being provided and will notify and cooperate with us regarding any requested or unauthorized disclosure or use of any Confidential Information.
