### ISSUE TITLE
Divide by 0 error in "set your own goal"

### ISSUE THREAD

**Issue by haraldnagel** [MCLD/greatreadingadventure#90]
1. Clean database
2. Set program to run from 3/1/2016 to 3/31/2016
3. Registration Settings -> turn on Daily Goal "Ask For", "Show on Profile", "Edit on Profile"
4. Award Triggers -> Add -> 1 point, 10% goal
5. Register for account, enter daily goal of 5 minutes
6. Log 10 minutes of reading
7. Division by 0 error in `app_Award_GetPatronQualifyingAwards`

**Comment by justinmeiners** [comment]
I thought I caught all those, but I will fix that tomorrow. Thanks!

**Comment by haraldnagel** [comment]
No problem at all! Thanks for contributing excellent code back to the project!

**Comment by justinmeiners** [comment]
This should be closed.
