### ISSUE TITLE
Controls/PatronLogin appears unused

### ISSUE THREAD

**Issue by justinmeiners** [MCLD/greatreadingadventure#91]
It appears that the PatronLogin.acsx is no longer being used and has been replaced by the login popup found in Layout/SRP.master. Is this correct? Should this be removed?

**Comment by haraldnagel** [comment]
The `PatronLogin.ascx` is still used in `Login.aspx` which I've left in the project since the login popup requires JavaScript and I was trying to make the site as functional as possible for users who might have JavaScript disabled (or were on a device that didn't have good JavaScript support).

**Comment by justinmeiners** [comment]
Ok good to know. This can be closed.
