### ISSUE TITLE
Trigger add failure causes Award Attachment functionality to be inaccessible

### ISSUE THREAD

**Issue by k7hpn** [MCLD/greatreadingadventure#994]
If the initial submit doesn't work from a trigger, when the page refreshes with an error message the attachment accordion is blank.

## Steps to reproduce

1. Access `/MissionControl/Triggers`
2. Choose: Create a new trigger
3. Fill out the form as such:
   1. Populate Name
   2. Do **not** populate Secret code
   3. Populate Notification, Badge Alternative Text, and select an image
   4. Expand the 'Award Attachment' accordion
   5. Upload a valid PDF by choosing Select a file
4. Choose: Create Trigger

## Expected behavior

1. Page reloads
2. Red error message about missing Secret code
3. The 'Award Attachment' accordion allows the user to select a valid PDF file again

## Actual behavior

1. Page reloads
2. Red error message about missing Secret code
3. The 'Award Attachment' accordion is open (correct) but is blank

**Comment by rprollingerjr** [comment]
:/ On it.


[cid:maricopacounty_logo_web_200px_wide_3643a012-bb30-4ec9-84b1-a1bd801b395f.png]       Paul Rollinger

LIBRARY DISTRICT
ADMINISTRATION

Web Designer/Developer
602-295-7041
MCLDAZ.ORG<https://www.mcldaz.org/>
Facebook<https://www.facebook.com/MaricopaLibraryDistrict/> | Instagram<https://www.instagram.com/maricopalibrarydistrict/> | Twitter<https://twitter.com/maricopaconnect/> | ***@***.***>

**Comment by rprollingerjr** [comment]
H.P.,

Sent a pull request for this issue. Check it out when you have a chance!
Thanks


[cid:maricopacounty_logo_web_200px_wide_3643a012-bb30-4ec9-84b1-a1bd801b395f.png]       Paul Rollinger

LIBRARY DISTRICT
ADMINISTRATION

Web Designer/Developer
602-295-7041
MCLDAZ.ORG<https://www.mcldaz.org/>
Facebook<https://www.facebook.com/MaricopaLibraryDistrict/> | Instagram<https://www.instagram.com/maricopalibrarydistrict/> | Twitter<https://twitter.com/maricopaconnect/> | ***@***.***>
